# Used to assign a label (like /snapshot/latest or /v0) to a published API
# snapshot (like /snapshot/123).
#
name: Label API Snapshot.

on:
  # Hook to trigger a manual run.
  # See: https://goobar.io/2019/12/07/manually-trigger-a-github-actions-workflow/
  repository_dispatch:
    types: label-api-snapshot

  # To debug, uncomment the stanza below. Fill in your own branch name,
  # hardcode LABEL and SNAPSHOT_ID below, and then each push will trigger a run.
  #
  # push:
  #   branches:
  #   - mikelehen/label-api

jobs:
  label-api-snapshot:
    runs-on: ubuntu-latest

    env:
      AWS_S3_BUCKET: 'covidactnow-deleteme'
      LABEL: '${{ github.event.client_payload.label }}'
      SNAPSHOT_ID: '${{ github.event.client_payload.snapshot_id }}'

    steps:
    - name: Slack notification
      if: always() # Pick up events even if the job fails or is canceled.
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: dev-alerts
        STATUS: ${{job.status}}
      uses: Ilshidur/action-slack@fb92a78
      with:
        args: 'Action to label {{SNAPSHOT_ID}} as {{LABEL}}. Job status: {{STATUS}}'
