name: Python Unit Tests

on: [push]

jobs:
  build:
    env:
      COVID_DATA_PUBLIC_REF: 'master'

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.6, 3.5]

    steps:
    - name: Checkout covid-data-public
      uses: actions/checkout@v2
      with:
        repository: covid-projections/covid-data-public
        path: covid-data-public
        lfs: true
        ref: '${{env.COVID_DATA_PUBLIC_REF}}'
