name: Update to new Data Snapshot

on:
  push:

env:
  AWS_S3_BUCKET: content.covidactnow.org
  # To pin to an old data set or model code, put the branch/tag/commit here:
  BRANCH: mikelehen/test-sharing
  SNAPSHOT_ID: 299
  IMAGES_ID: 299-${{github.run_number}}

jobs:
  update-to-new-snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: covid-projections/covid-projections
          ref: '${{ env.BRANCH }}'
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install
      - run: 'echo "{ \"data_url\": \"https://data.covidactnow.org/snapshot/${{env.SNAPSHOT_ID}}/\" }" > src/assets/data/data_url.json'
      - run: yarn update-calculated-interventions
      - run: yarn start &
      - run: sleep 15
      - run: yarn generate-share-images
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: scripts/generate_share_images/output
          DEST_DIR: share/${{env.IMAGES_ID}}
      - run: 'echo "{ \"share_image_url\": \"https://content.covidactnow.org/share/${{env.IMAGES_ID}}/\" }" > src/assets/data/share_images_url.json'
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          draft: true
          branch: 'bump-snapshot-${{env.SNAPSHOT_ID}}'
          branch-suffix: random
          commit-message: >
            Update to data snapshot ${{env.SNAPSHOT_ID}}.

            * Regenerate calculated interventions files.
            * Point at updated share images.
          title: Update to data snapshot ${{env.SNAPSHOT_ID}}
          body: >
            Update to data snapshot ${{env.SNAPSHOT_ID}}.

            * Regenerate calculated interventions files.
            * Point at updated share images.
