name: Update source data

on:
  schedule:
    - cron: '0,5,10,15,20,25,30,35,40,45,55 * * * *'
  # Hook to trigger a manual run. 
  # See: https://goobar.io/2019/12/07/manually-trigger-a-github-actions-workflow/
  repository_dispatch:
    types: update-source-data
# To debug, comment out above schedule, and uncomment the stanza below.
# Fill in your own branch name, and each push will trigger a run
#  push:
#    branches:
#    - <YOUR BRANCH HERE>

jobs:
  update-source-data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7.6'
        architecture: 'x64'
    - name: Cache Pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install Dependencies
      run: pip install -r requirements.txt
    - name: Update Datasets
      run: ./update.sh
    - name: Create Update Commit
      run: ./push_update.sh
        
